### PR TITLE
Add support for MySQL 8.0.20

### PR DESCRIPTION
**Pull request by victor-eblock**
It works for Mac OS X but I can't verify Win or Nix downloaders. Please double check it works for you. Thanks

### CODE REVIEW

**Review by oryan-block — APPROVED** [review]
- I ran `clean install` on the branch
- I ran tests on edealer with:
```
        <dependency>
	    <groupId>com.github.carmigo.embedded-mysql</groupId>
	    <artifactId>wix-embedded-mysql</artifactId>
	    <version>support-mysql-8-20-SNAPSHOT</version>
	</dependency>
```

So I believe this works on win10

**Comment by victor-eblock** [comment]
> So I believe this works on win10

Well, there's one last thing you need to do for our project. In `CoreTestConfiguration` you need to change the version from `v8_0_17` to `v8_0_20` which is the latest. We know 8.0.17 works. 🙈

**Comment by oryan-block** [comment]
> one last thing 

Good news. That works too

**Comment by victor-eblock** [comment]
> Good news. That works too

Noice. Now I only need it to run on CircleCI and that's as far as I'll get running it on Linux.

**Pull request merged**
